const { getEmailHeader } = require('../utils/emailHeaderHelper');

/**
 * Generates the HTML welcome email template with invitation credentials for new employees.
 * 
 * @param {string} employeeName - New employee's name.
 * @param {string} companyName - Registering company organization name.
 * @param {string} email - Employee login email identifier.
 * @param {string} tempPassword - Plain text temporary password.
 * @param {string} portalUrl - Custom URL of the employee self-service login.
 * @returns {string} Fully styled HTML template string.
 */
function employeeInvitationTemplate(employeeName, companyName, email, tempPassword, portalUrl) {
  const finalPortalUrl = portalUrl || 'http://localhost:5173/employee/login';
  const year = new Date().getFullYear();
  const headerHtml = getEmailHeader('Duskra Invitation Node', `${companyName || 'Company'} Workspace Access`);

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Welcome to ${companyName}</title>
      <style>
        body {
          margin: 0;
          padding: 0;
          background-color: #F8FAFC;
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
          color: #334155;
        }
        .container {
          max-width: 600px;
          margin: 40px auto;
          background-color: #ffffff;
          border: 1px solid #E2E8F0;
          border-radius: 16px;
          overflow: hidden;
          box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -2px rgba(0, 0, 0, 0.05);
        }
        .content {
          padding: 32px;
        }
        .welcome-text {
          font-size: 15px;
          line-height: 1.6;
          color: #334155;
          margin-top: 0;
          margin-bottom: 24px;
        }
        .credentials-card {
          background-color: #F8FAFC;
          border: 1px solid #E2E8F0;
          border-radius: 12px;
          padding: 24px;
          margin-bottom: 24px;
        }
        .credentials-card h3 {
          margin: 0 0 16px 0;
          font-size: 14px;
          color: #475569;
          text-transform: uppercase;
          letter-spacing: 0.5px;
        }
        .field-group {
          margin-bottom: 16px;
        }
        .field-group:last-child {
          margin-bottom: 0;
        }
        .field-label {
          display: block;
          font-size: 12px;
          color: #64748B;
          font-weight: 600;
          margin-bottom: 4px;
          text-transform: uppercase;
        }
        .field-value {
          font-size: 15px;
          color: #0F172A;
          font-weight: 700;
          word-break: break-all;
        }
        .temp-password {
          font-family: Menlo, Monaco, Consolas, "Courier New", monospace;
          background-color: #FEF3C7;
          color: #92400E;
          padding: 6px 12px;
          border-radius: 6px;
          border: 1px inline-block #FCD34D;
          letter-spacing: 1px;
        }
        .btn-container {
          text-align: center;
          margin: 32px 0;
        }
        .btn {
          display: inline-block;
          background-color: #2563EB;
          color: #ffffff !important;
          text-decoration: none;
          padding: 14px 28px;
          border-radius: 8px;
          font-weight: 700;
          font-size: 15px;
          box-shadow: 0 4px 6px -1px rgba(37, 99, 235, 0.2);
        }
        .warning-box {
          background-color: #FFFBEB;
          border-left: 4px solid #F59E0B;
          border-radius: 8px;
          padding: 16px;
          margin: 24px 0;
          font-size: 13px;
          line-height: 1.5;
          color: #B45309;
        }
        .footer {
          background-color: #F8FAFC;
          border-top: 1px solid #E2E8F0;
          padding: 24px;
          text-align: center;
          font-size: 12px;
          color: #94A3B8;
        }
        .footer a {
          color: #64748B;
          text-decoration: none;
          margin: 0 8px;
        }
        .footer a:hover {
          text-decoration: underline;
        }
      </style>
    </head>
    <body>
      <div class="container">
        ${headerHtml}
        <div class="content">
          <p class="welcome-text">Hello <strong>${employeeName}</strong>,</p>
          <p class="welcome-text">Your workspace profile has been successfully generated by your company administrator. You can now access the company Employee Portal using the temporary credentials detailed below.</p>
          
          <div class="credentials-card">
            <h3>Login Credentials</h3>
            <div class="field-group">
              <span class="field-label">Workspace Portal URL</span>
              <div class="field-value"><a href="${finalPortalUrl}" style="color: #2563EB;">${finalPortalUrl}</a></div>
            </div>
            <div class="field-group">
              <span class="field-label">Authorized Work Email</span>
              <div class="field-value">${email}</div>
            </div>
            <div class="field-group">
              <span class="field-label">Temporary Passcode</span>
              <div class="field-value"><span class="temp-password">${tempPassword}</span></div>
            </div>
          </div>

          <div class="btn-container">
            <a href="${finalPortalUrl}" class="btn" target="_blank">Access Employee Portal</a>
          </div>

          <div class="warning-box">
            <strong>⏰ Action Required:</strong> Please change your temporary passcode immediately upon your first sign in to ensure account security.
          </div>
        </div>

        <div class="footer">
          <p>&copy; ${year} Duskra Platform. All rights reserved.</p>
          <p>
            <a href="${finalPortalUrl}">Employee Portal</a> &bull;
            <a href="mailto:support@duskra.com">Support</a>
          </p>
        </div>
      </div>
    </body>
    </html>
  `;
}

module.exports = employeeInvitationTemplate;
