const PAGE_WIDTH = 595;
const PAGE_HEIGHT = 842;
const MARGIN_X = 54;
const TOP_Y = 790;
const BOTTOM_Y = 56;
const LINE_HEIGHT = 15;
const MAX_TEXT_CHARS = 92;

function cleanText(value) {
  return String(value ?? "")
    .replace(/\u20b9/g, "INR ")
    .replace(/[^\x20-\x7E]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function escapePdfText(value) {
  return cleanText(value).replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)");
}

function wrapText(value, maxChars = MAX_TEXT_CHARS) {
  const text = cleanText(value);
  if (!text) return ["-"];

  const words = text.split(" ");
  const lines = [];
  let line = "";

  words.forEach((word) => {
    if (word.length > maxChars) {
      if (line) {
        lines.push(line);
        line = "";
      }
      for (let i = 0; i < word.length; i += maxChars) {
        lines.push(word.slice(i, i + maxChars));
      }
      return;
    }

    const next = line ? `${line} ${word}` : word;
    if (next.length > maxChars) {
      lines.push(line);
      line = word;
    } else {
      line = next;
    }
  });

  if (line) lines.push(line);
  return lines.length ? lines : ["-"];
}

function addText(commands, text, x, y, size = 10) {
  commands.push(`BT /F1 ${size} Tf 1 0 0 1 ${x} ${y} Tm (${escapePdfText(text)}) Tj ET`);
}

function addRule(commands, y) {
  commands.push(`0.78 w ${MARGIN_X} ${y} m ${PAGE_WIDTH - MARGIN_X} ${y} l S`);
}

function createFormalReportPdf({ title, subtitle, meta = [], sections = [] }) {
  const pages = [];
  let commands = [];
  let y = TOP_Y;

  const startPage = () => {
    commands = [];
    y = TOP_Y;
    addText(commands, title || "Report", MARGIN_X, y, 18);
    y -= 20;
    if (subtitle) {
      addText(commands, subtitle, MARGIN_X, y, 10);
      y -= 18;
    }
    addRule(commands, y);
    y -= 18;
  };

  const finishPage = () => {
    addRule(commands, 42);
    addText(commands, `Generated by Duskra SaaS - Page ${pages.length + 1}`, MARGIN_X, 28, 8);
    pages.push(commands.join("\n"));
  };

  const ensureSpace = (needed = LINE_HEIGHT) => {
    if (y - needed >= BOTTOM_Y) return;
    finishPage();
    startPage();
  };

  startPage();

  meta.forEach(([label, value]) => {
    ensureSpace();
    addText(commands, `${label}: ${value || "-"}`, MARGIN_X, y, 10);
    y -= LINE_HEIGHT;
  });

  y -= 6;

  sections.forEach((section) => {
    ensureSpace(34);
    addText(commands, section.heading, MARGIN_X, y, 13);
    y -= 12;
    addRule(commands, y);
    y -= 15;

    if (section.type === "table") {
      const headers = section.headers || [];
      const colWidths = section.widths || [];
      const startX = MARGIN_X;

      const drawHeader = () => {
        ensureSpace(20);
        // Sleek dark banner background for header row
        commands.push(`q 0.2 0.22 0.28 rg ${MARGIN_X - 4} ${y - 4} ${PAGE_WIDTH - 2 * MARGIN_X + 8} 15 re f Q`);

        let curX = startX;
        headers.forEach((header, i) => {
          commands.push("q 1 1 1 rg"); // White text for headers

          addText(commands, header, curX, y, 8.5);
          commands.push("Q");
          curX += colWidths[i] || 80;
        });
        y -= 12;
        y -= 12;
      };

      drawHeader();

      if (!section.rows || section.rows.length === 0) {
        ensureSpace();
        addText(commands, section.emptyText || "No records available.", MARGIN_X, y, 10);
        y -= LINE_HEIGHT;
        return;
      }

      section.rows.forEach((row, rowIndex) => {
        const curPageCount = pages.length;
        ensureSpace(18);
        if (pages.length > curPageCount) {
          drawHeader();
        }

        // Alternating row background for clean readability
        if (rowIndex % 2 === 1) {
          commands.push(`q 0.95 0.96 0.98 rg ${MARGIN_X - 4} ${y - 4} ${PAGE_WIDTH - 2 * MARGIN_X + 8} 14 re f Q`);
        }

        let curX = startX;
        row.forEach((cell, i) => {
          addText(commands, String(cell || ""), curX, y, 8);
          curX += colWidths[i] || 80;
        });
        y -= LINE_HEIGHT;
        commands.push(`0.3 w ${MARGIN_X} ${y + 3} m ${PAGE_WIDTH - MARGIN_X} ${y + 3} l S`);
      });
      y -= 6;
      return;
    }

    if (!section.rows || section.rows.length === 0) {
      ensureSpace();
      addText(commands, section.emptyText || "No records available.", MARGIN_X, y, 10);
      y -= LINE_HEIGHT;
      y -= 5;
      return;
    }

    section.rows.forEach((row, index) => {
      ensureSpace(LINE_HEIGHT * 2);
      const prefix = section.numbered === false ? "" : `${index + 1}. `;
      const lines = wrapText(`${prefix}${row}`);
      lines.forEach((line) => {
        ensureSpace();
        addText(commands, line, MARGIN_X, y, 10);
        y -= LINE_HEIGHT;
      });
      y -= 3;
    });

    y -= 6;
  });

  finishPage();

  const objects = [];
  const pageObjects = [];
  const contentObjects = [];

  pages.forEach((content, index) => {
    pageObjects.push(4 + index * 2);
    contentObjects.push(5 + index * 2);
  });

  objects[1] = `<< /Type /Catalog /Pages 2 0 R >>`;
  objects[2] = `<< /Type /Pages /Kids [${pageObjects.map((id) => `${id} 0 R`).join(" ")}] /Count ${pages.length} >>`;
  objects[3] = `<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>`;

  pages.forEach((content, index) => {
    const pageId = pageObjects[index];
    const contentId = contentObjects[index];
    const contentLength = Buffer.byteLength(content, "ascii");
    objects[pageId] = `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${PAGE_WIDTH} ${PAGE_HEIGHT}] /Resources << /Font << /F1 3 0 R >> >> /Contents ${contentId} 0 R >>`;
    objects[contentId] = `<< /Length ${contentLength} >>\nstream\n${content}\nendstream`;
  });

  let pdf = "%PDF-1.4\n";
  const offsets = [0];

  for (let i = 1; i < objects.length; i += 1) {
    offsets[i] = Buffer.byteLength(pdf, "ascii");
    pdf += `${i} 0 obj\n${objects[i]}\nendobj\n`;
  }

  const xrefOffset = Buffer.byteLength(pdf, "ascii");
  pdf += `xref\n0 ${objects.length}\n`;
  pdf += "0000000000 65535 f \n";
  for (let i = 1; i < objects.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`;
  }
  pdf += `trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, "ascii");
}

module.exports = { createFormalReportPdf, cleanText };
